#!/bin/python3

import math
import os
import random
import re
import sys

#
# Complete the 'diagonalDifference' function below.
#
# The function is expected to return an INTEGER.
# The function accepts 2D_INTEGER_ARRAY arr as parameter.
#

def diagonalDifference(arr):
    # Write your code here
    size=len(arr)
    rd=0
    ld=0

    for i in range(0,size):
        for j in range(0,size):
            if (i==j) and (i+j==len(arr)-1) :
                continue 
            elif i==j:
                ld=ld+arr[i][j]
                # print(arr[i][j])
            elif i+j==len(arr)-1:
                # print(arr[i][j].index())
                rd=rd+arr[i][j]
    return(abs(rd-ld))

if __name__ == '__main__':
    fptr = open(os.environ['OUTPUT_PATH'], 'w')

    n = int(input().strip())

    arr = []

    for _ in range(n):
        arr.append(list(map(int, input().rstrip().split())))

    result = diagonalDifference(arr)

    fptr.write(str(result) + '\n')

    fptr.close()
