#!/bin/python3

import math
import os
import random
import re
import sys

#
# Complete the 'plusMinus' function below.
#
# The function accepts INTEGER_ARRAY arr as parameter.
#

def plusMinus(arr):
    # Write your code here
    neg=0
    pos=0
    zero=0
    for i in arr:
        if i<0:
            neg=neg+1;
        elif i>0:
            pos=pos+1
        else:
            zero=zero+1

    neg1=neg/len(arr)
    pos1=pos/len(arr)
    zero1=zero/len(arr)
    print('%6f'%pos1)
    print('%6f'%neg1)
    print('%6f'%zero1)

if __name__ == '__main__':
    n = int(input().strip())

    arr = list(map(int, input().rstrip().split()))

    plusMinus(arr)
